# Generated by Django 3.2.4 on 2021-06-21 17:48

import app.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', app.models.TinyIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('content', models.TextField(default='')),
                ('parent_comment_uuid', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comment')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', app.models.TinyIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('caption', models.TextField(default='', null=True)),
                ('image_url', models.CharField(default=None, max_length=255, null=True)),
                ('video_url', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', app.models.TinyIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=45)),
                ('image_url', models.CharField(default='', max_length=255)),
                ('bio', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', app.models.TinyIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('value', models.IntegerField(default=0)),
                ('post_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'vote',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', app.models.TinyIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(default='', max_length=255)),
                ('desc', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default=None, max_length=255, null=True)),
                ('category', models.CharField(default=None, max_length=45)),
                ('source_name', models.CharField(max_length=45)),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.user')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', app.models.TinyIntegerField(default=0)),
                ('token', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', app.models.TinyIntegerField(default=0)),
                ('uuid', models.CharField(max_length=45)),
                ('followed_user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='app.user')),
                ('follower_user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='app.user')),
            ],
            options={
                'db_table': 'relationship',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='topic_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topic'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', app.models.TinyIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('value', models.IntegerField(default=0)),
                ('comment_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comment')),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'comment_vote',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
