# Generated by Django 3.2.4 on 2021-06-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userprofile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment_uuid',
            new_name='parent_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_uuid',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_uuid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commentvote',
            old_name='comment_uuid',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentvote',
            old_name='user_uuid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='topic_uuid',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_uuid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='followed_user_uuid',
            new_name='followed_user',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='follower_user_uuid',
            new_name='follower_user',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='user_uuid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='user_uuid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='post_uuid',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user_uuid',
            new_name='user',
        ),
    ]
